### ISSUE TITLE
simplemaphelper not working?

### ISSUE THREAD

**Issue by nathanielperales** [engram-design/FeedMe-Helpers#4]
Trying to import longitude and latitude into entries via simplemap and with this plugin it seems to just hang?

Wondering if anyone else is having that issue. 

I tried importing the data to Plain Text fields and the data imports just fine. This is the error I'm getting if I look at the debugger:

`Undefined index: lat`

**Comment by engram-design** [comment]
Without looking at your feed, its difficult to troubleshoot this. I've used the following, which is working:

```
<SimpleMap>
  <lat>-37.8012579</lat>
  <lng>144.95069009999997</lng>
</SimpleMap>
```

![screen shot 2017-09-20 at 7 34 47 pm](https://user-images.githubusercontent.com/1221575/30637115-cb427baa-9e3a-11e7-80d2-3cb084f1738c.png)

**Comment by nathanielperales** [comment]
Hey thanks so much for the quick response. So I think it's something with the json feed. This is an example of what I'm trying to get: https://app.ticketmaster.com/discovery/v2/events.json?attractionId=K8vZ9175YiV&apikey=Pt1YosXJ3mJEpoiAjdWvPHogF1ChKWeg - trying to get the venues data in line 210. Any help is much appreciated, thanks!

**Comment by nathanielperales** [comment]
Okay looking at the debugger it seems it's because it's an array: 

[venueAddress] => Array
        (
            [0] => 
        )

And it can't properly map the array, do you have any solutions that might fix that?

The other thing that's strange is it fits perfectly with plain text fields, just not the mapping field.

**Comment by engram-design** [comment]
@nathanielperales Are you able to submit a help request through Feed Me? I need to look at your feed setup. Or feel free to ping me on slack (`@crawf`)

**Comment by nathanielperales** [comment]
Just figured it out, I'll message you on slack.
